# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'GiphyViewer' do
	use_frameworks!

	# Pods for GiphyViewer
	pod 'SnapKit'
	pod 'Gifu'
	pod 'PINCache'

	target 'GiphyViewerTests' do
		inherit! :search_paths
		# Pods for testing
	end

	target 'GiphyViewerUITests' do
		# Pods for testing
	end
end
